actors:
  lsd:
    image_url: /images/actors/lsd.jpg
    name: 川上
    url: https://twitter.com/lsd_jp
  gema:
    image_url: /images/actors/gema.jpg
    name: 円谷
    url: https://twitter.com/___35d
  aruru:
    image_url: /images/actors/aruru.jpg
    name: aruru
    url: http://sns.example.com/bob
  coco:
    image_url: /images/actors/coco.jpg
    name: 古後
    url: http://sns.example.com/bob
author: BizReach, Inc.
description: 株式会社ビズリーチのデザイナーが最近気になっていることを喋りまくる、ながら聞き推奨Podcastです。
description_long: 株式会社ビズリーチのデザイナーが最近気になっていることを喋りまくる、ながら聞き推奨Podcastです。
email: bdpfm@bizreach.co.jp
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: bfpfm
itunes_podcast_url: 
keywords: bfpfm
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: bdpfm
url: https://twitter.com/bdpfm
